import React, { useEffect, useState } from "react";
import * as fcl from "@onflow/fcl";
import Head from "next/head";
import * as t from "@onflow/types";

import Nav from "../general/Nav";
import Footer from "../general/Footer";
import { fetchOneUser } from "../profile/transactions";

fcl
  .config()
  .put(
    "accessNode.api",
    process.env.ACCESS_NODE || "https://access-testnet.onflow.org"
  )
  .put(
    "challenge.handshake",
    process.env.WALLET || "https://flow-wallet-testnet.blocto.app/authn"
  )
  .put("0xFungibleToken", process.env.FUNGIBLE_TOKEN || "0x9a0766d93b6608b7")
  .put(
    "0xNonFungibleToken",
    process.env.NONFUNGIBLE_TOKEN || "0x631e88ae7f1d7c20"
  )
  .put("0xFlowToken", process.env.FLOW_TOKEN || "0x7e60df042a9c0868")
  .put("0xCONTRACT", process.env.CONTRACT || "0xdb47998bf96c9ef1")
  .put("env", process.env.FLOW_ENV || "testnet");

const Main = ({ children }) => {
  const [user, setUser] = useState({ loggedIn: null });
  const [balance, setBalance] = useState(0);
  useEffect(() => fcl.currentUser().subscribe(setUser), []);
  useEffect(() => {
    async function getArt() {
      const response = await fcl.send([
        fcl.script(fetchOneUser),
        fcl.args([fcl.arg(user.addr, t.Address)]),
      ]);
      const balance = await fcl.decode(response);
      setBalance(parseFloat(balance).toFixed(2));
    }
    if (user.addr) getArt();
  }, [user.addr]);
  return (
    <>
      <Head>
        <title>Versus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav user={user} balance={balance} />
      {typeof children === String
        ? React.cloneElement(children, { user })
        : children(user)}
      <Footer />
    </>
  );
};

export default Main;
